DEBUG = false;
fade_to_black = 0;
fade_to_black_goal = 1;
fade_to_black_time = 0;
fade_to_black_start = 0;
fade_to_black_interpol = lerp;
notes = {};

COLORS = [
    "#8AAC09",
    "#FD13DC",
    "black",
    "#0F9BF2",
    "#FEAF20",
    "black",
    "black",
    "#F20C0C",
    "black",
    "black",
    "black",
    "black",
    "black",
    "black",
    "black",
    "black"
];

/* smoothstep interpolaties between a and b, at time t from 0 to 1 */
function smoothstep(a, b, t){
    var v = t*t*(3-2*t);
    return b*v + a*(1-v);
};

function lerp(a,b,t){
    return b*t + a*(1-t);
}

function update(){
    for(var i in notes){
        var note = notes[i];
        note.timepassed+=midi.ticks_per_second/1000*20;
    }
}

function render(ctx){
    var analyser_bands =1024;
    c.width=c.width;
    freqData = new Uint8Array(mixer.analyser.frequencyBinCount);
    mixer.analyser.getByteFrequencyData(freqData);
    var intensity = 0;
    var j = 0;
    x.fillStyle = "#cccccc";
    for(var i=0;i<freqData.length;i++){
        intensity += freqData[i];
        if(j>freqData.length/analyser_bands){
            j=0;
            intensity /= 256;
            intensity /= freqData.length/analyser_bands;
            x.fillRect(((0|(i/freqData.length*analyser_bands))-1)*GU/analyser_bands*16, (9-intensity)*GU, GU/analyser_bands*16, intensity*GU);

            intensity = 0;
        }
        j++;
    }
    intensity /= 256;
    intensity /= freqData.length/analyser_bands;
    x.fillRect(((0|(i/freqData.length*analyser_bands))-1)*GU/analyser_bands*16, (9-intensity)*GU, GU/analyser_bands*16, intensity*GU);

    for(var i in notes){
        var note = notes[i];
        x.fillStyle = note.color;
        ctx.beginPath();
        ctx.moveTo(note.x*GU, note.y*GU);
        ctx.lineTo((note.x+1)*GU,note.y*GU);
        ctx.arc(note.x*GU, note.y*GU, GU/2, 0,(1-note.timepassed/note.maxtimeleft)*Math.PI*2, true); 
        ctx.closePath();
        ctx.fill();
    }
    x.fillStyle = "white";
    for(var i in notes){
        var note = notes[i];
        ctx.beginPath();
        ctx.arc(GU*note.x, GU*note.y, GU*0.8/4, 0,Math.PI*2, true); 
        ctx.closePath();
        ctx.fill();
    }
    for(var i in notes){
        var note = notes[i];
        x.fillStyle = note.color;
        ctx.beginPath();
        ctx.arc(GU*note.x, GU*note.y, GU*0.6/4, 0,Math.PI*2, true); 
        ctx.closePath();
        ctx.fill();
    }
}


function init(){
debug("entering init");
    
var data = "TVRoZAAAAAYAAQAFAYBNVHJrAAAAGgD/WAQEAmAIAP9/AwAAQQD/UQMKJmQA/y8ATVRyawAACEQA/wMLR3JhbmQgUGlhbm8AsAAAAMAuAP9ZAgQAAJBOZACQR2QAkFNkgUCATgAAkExkgUCATAAAkEtkgUCASwAAkElkgUCARwAAgFMAAIBJAACQTGQAkEBkAJBQZIFAgEwAAJBLZIFAgEsAAJBJZIFAgEkAAJBHZIFAgEAAAIBQAACARwAAkEdkAJBEZACQU2RggEcAAJBJZGCASQAAkEtkYIBLAACQSWSIIIBJAACQR2SBQIBEAACAUwAAgEcAAJBHZACQQGQAkExkhgCARwAAgEAAAIBMAACQSWQAkEJkAJBOZIYAgEkAAIBCAACATgAAkEdkgUCARwAAkEtGgUCASwAAkE5GgUCATgAAkFNGgUCAUwAAkERGgUCARAAAkEdGgUCARwAAkEtGgUCASwAAkE5GgUCATgAAkElGgUCASQAAkExGgUCATAAAkFBGgUCAUAAAkFVGgUCAVQAAkEJGgUCAQgAAkEZGgUCARgAAkElGgUCASQAAkE5GgUCATgAAkEdGgUCARwAAkEtGgUCASwAAkE5GgUCATgAAkFNGgUCAUwAAkERGgUCARAAAkEdGgUCARwAAkEtGgUCASwAAkE5GgUCATgAAkEZGgUCARgAAkEtGgUCASwAAkE5GgUCATgAAkFJGgUCAUgAAkFdGgUCAVwAAkFJGgUCAUgAAkE5GgUCATgAAkEtGgUCASwAAkERGgUCARAAAkEdGgUCARwAAkEtGgUCASwAAkFBGgUCAUAAAkEZGgUCARgAAkEtGgUCASwAAkE5GgUCATgAAkFJGgUCAUgAAkExGgUCATAAAkFBGgUCAUAAAkFNGgUCAUwAAkFhGgUCAWAAAkEdGgUCARwAAkEtGgUCASwAAkE5GgUCATgAAkFNGgUCAUwAAkEQ3gUCARAAAkEc3gUCARwAAkEs3gUCASwAAkFA3gUCAUAAAkEk3gUCASQAAkEw3gUCATAAAkFA3gUCAUAAAkFU3gUCAVQAAkEc3gUCARwAAkEs3gUCASwAAkE43gUCATgAAkFM3gUCAUwAAkFU3gUCAVQAAkFM3gUCAUwAAkFI3gUCAUgAAkE43gUCATgAAkEw3gUCATAAAkFA3gUCAUAAAkFM3gUCAUwAAkFg3gUCAWAAAkEY3gUCARgAAkEk3gUCASQAAkEw3gUCATAAAkFI3gUCAUgAAkEk3gUCASQAAkEw3gUCATAAAkFM3gUCAUwAAkFc3gUCAVwAAkFc3gUCAVwAAkFU3gUCAVQAAkFQ3gUCAVAAAkFA3gUCAUAAAkEk3gUCASQAAkEw3gUCATAAAkFA3gUCAUAAAkFU3gUCAVQAAkEc3gUCARwAAkEs3gUCASwAAkE43gUCATgAAkFM3gUCAUwAAkEc3gUCARwAAkEs3gUCASwAAkE43gUCATgAAkFM3gUCAUwAAkFc3gUCAVwAAkFM3gUCAUwAAkE43gUCATgAAkEs3gUCASwAAkEc3gUCARwAAkEs3gUCASwAAkE43gUCATgAAkFM3gUCAUwAAkEQ3gUCARAAAkEc3gUCARwAAkEs3gUCASwAAkE43gUCATgAAkEk3gUCASQAAkEw3gUCATAAAkFA3gUCAUAAAkFU3gUCAVQAAkEI3gUCAQgAAkEY3gUCARgAAkEk3gUCASQAAkE43gUCATgAAkEc3gUCARwAAkEs3gUCASwAAkE43gUCATgAAkFM3gUCAUwAAkEQ3gUCARAAAkEc3gUCARwAAkEs3gUCASwAAkE43gUCATgAAkEY3gUCARgAAkEs3gUCASwAAkE43gUCATgAAkFI3gUCAUgAAkFc3gUCAVwAAkFI3gUCAUgAAkE43gUCATgAAkEs3gUCASwAAkEQ3gUCARAAAkEc3gUCARwAAkEs3gUCASwAAkFA3gUCAUAAAkEY3gUCARgAAkEs3gUCASwAAkE43gUCATgAAkFI3gUCAUgAAkExAgUCATAAAkFBAgUCAUAAAkFNAgUCAUwAAkFhAgUCAWAAAkEc3gUCARwAAkEs3gUCASwAAkE43gUCATgAAkFM3gUCAUwAAkEQ3gUCARAAAkEc3gUCARwAAkEs3gUCASwAAkFA3gUCAUAAAkEk3gUCASQAAkEw3gUCATAAAkFA3gUCAUAAAkFU3gUCAVQAAkEc3gUCARwAAkEs3gUCASwAAkE43gUCATgAAkFM3gUCAUwAAkFU3gUCAVQAAkFM3gUCAUwAAkFI3gUCAUgAAkE43gUCATgAAkEw3gUCATAAAkFA3gUCAUAAAkFM3gUCAUwAAkFg3gUCAWAAAkEY3gUCARgAAkEk3gUCASQAAkEw3gUCATAAAkFI3gUCAUgAAkEk3gUCASQAAkEw3gUCATAAAkFM3gUCAUwAAkFc3gUCAVwAAkFc3gUCAVwAAkFU3gUCAVQAAkFQ3gUCAVAAAkFA3gUCAUAAAkEk3gUCASQAAkEw3gUCATAAAkFA3gUCAUAAAkFU3gUCAVQAAkEc3gUCARwAAkEs3gUCASwAAkE43gUCATgAAkFM3gUCAUwAAkEc3gUCARwAAkEs3gUCASwAAkE43gUCATgAAkFM3gUCAUwAAkFc3gUCAVwAAkFM3gUCAUwAAkE43gUCATgAAkEs3gUCASwAAkEk3gUCASQAAkEw3gUCATAAAkFA3gUCAUAAAkFU3gUCAVQAAkEc3gUCARwAAkEs3gUCASwAAkE43gUCATgAAkFM3gUCAUwAAkEc3gUCARwAAkEs3gUCASwAAkE43gUCATgAAkFM3gUCAUwAAkFc3gUCAVwAAkFM3gUCAUwAAkE43gUCATgAAkEs3gUCASwAA/y8ATVRyawAABPMA/wMRU3RyaW5nIEVuc2VtYmxlIDEAtwAAAMcwAP9ZAgAApACXQjIAly9AhgCHQgAAhy8AAJdCMgCXLECGAIdCAACHLAAAl0cyAJcxQIYAh0cAAIcxAACXRjIAlypAgwCHRgAAl0cygwCHKgAAh0cAAJdCMgCXL0CGAIdCAACHLwAAl0IyAJcsQIYAh0IAAIcsAACXQjIAlzNAhgCHQgAAhzMAAJdCMgCXLkCGAIdCAACHLgAAl0cyAJcsQIYAh0cAAIcsAACXRjIAlzNAhgCHRgAAhzMAAJdHMgCXNECDAIdHAACXSTKDAIc0AACHSQAAl0syAJcvQIMAh0sAAIcvAACXTDIAly5AgwCHTAAAhy4AAJdLMgCXLECGAIdLAACHLAAAl0kyAJcxQIYAh0kAAIcxAACXRzIAlypAhgCHRwAAl0kyhgCHKgAAh0kAAJdHMgCXKECGAIdHAACHKAAAl0kyAJcqQIYAh0kAAIcqAACXTDIAly9AgwCHTAAAhy8AAJdLMgCXLUCDAIdLAACHLQAAl04yAJcsQIYAh04AAIcsAACXTDIAlzFAhgCHTAAAhzEAAJdQMgCXKkCDAIdQAACXUjKDAIcqAACHUgAAl1MyAJcvQIwAh1MAAIcvAACXTksAly9AgwCHTgAAl1dLgwCHLwAAh1cAAJdYSwCXLECBQIdYAACXV0uBQIdXAACXVUuBQIdVAACXU0uBQIcsAACHUwAAl1pLAJcxQIRAh1oAAJdVS4FAhzEAAIdVAACXVUsAlypAhgCHVQAAhyoAAJdOSwCXL0CDAIdOAACXV0uDAIcvAACHVwAAl1hLAJcsQIFAh1gAAJdXS4FAh1cAAJdVS4FAh1UAAJdTS4FAhywAAIdTAACXWksAlzNAhgCHMwAAly5AgwCHWgAAl1xLgUCHXAAAl15LgUCHLgAAh14AAJdfSwCXLECDAIdfAACXXkuBQIdeAACXXEuBQIcsAACHXAAAl1pLAJczQIMAh1oAAJdXS4MAhzMAAIdXAACXXEsAlzRAgwCHXAAAl1pLgUCHWgAAl1hLgUCHNAAAh1gAAJdXSwCXL0CDAIdXAACHLwAAl1VLAJcuQIMAh1UAAIcuAACXU0sAlyxAgUCHUwAAl1JLgUCHUgAAl1NLgUCHUwAAl1dLgUCHLAAAh1cAAJdVSwCXMUCDAIdVAACXUEuBQIdQAACXU0uBQIcxAACHUwAAl1NLAJcqQIYAh1MAAJdVS4RAh1UAAJdaS4FAhyoAAIdaAACXXEsAlyhAgwCHXAAAl1pLgUCHWgAAl1xLgUCHKAAAh1wAAJdaSwCXKkCDAIdaAACXVUuBQIdVAACXWEuBQIcqAACHWAAAl1hLAJcvQIMAh1gAAIcvAACXV0sAly1AgUCHVwAAl1VLgUCHLQAAh1UAAJdUSwCXLECDAIdUAACXVUuBQIdVAACXV0uBQIcsAACHVwAAl1hLAJcxQIMAh1gAAJdXS4FAh1cAAJdVS4FAhzEAAIdVAACXU0sAlypAgwCHUwAAl1VLgwCHKgAAh1UAAJdTQACXL0CKQIdTAACXV0CBQIcvAACHVwAAl1hLAJcxQIMAh1gAAJdXS4FAh1cAAJdVS4FAhzEAAIdVAACXU0sAlypAgwCHUwAAl1VLgwCHKgAAh1UAAJdTQACXL0CMAIdTAACHLwAA/y8ATVRyawAAAaAA/wMHUGljY29sbwC0AAAAxEkA/1kCAACBxECUWChghFgAAJRXKGCEVwAAlFgogUCEWAAAlFcogUCEVwAAlFUogUCEVQAAlFMogUCEUwAAlFUogUCEVQAAlFcogUCEVwAAlE4ojwCETgAAlFBAhECEUAAAlFJAgUCEUgAAlFNAhgCEUwAAlFdAhgCEVwAAlFhAgUCEWAAAlFdAgUCEVwAAlFVAgUCEVQAAlFNAgUCEUwAAlFVAgUCEVQAAlFdAgUCEVwAAlE5AgwCETgAAlFNAiQCEUwAAlExAgwCETAAAlFBAhgCEUAAAlE5AhgCETgAAlFNAhgCEUwAAlFVAgwCEVQAAlE5AgUCETgAAlFJAgUCEUgCEQJRYQIFAhFgAAJRXQIYAhFcAAJRYS4MAhFgAAJRXS4FAhFcAAJRVS4FAhFUAAJRTS4MAhFMAAJRVS4MAhFUAAJRTQIpAhFMAAJRXQIFAhFcAAJRYS4MAhFgAAJRXS4FAhFcAAJRVS4FAhFUAAJRTS4MAhFMAAJRVS4MAhFUAAJRTQIwAhFMAAP8vAE1UcmsAAAcuAP8DBkZsdXRlMgCzAAAAw0gA/1kCAACkAJNOS4MAg04AAJNXS4MAg1cAAJNYS4FAg1gAAJNXS4FAg1cAAJNVS4FAg1UAAJNTS4FAg1MAAJNaS4RAg1oAAJNVS4FAg1UAAJNVS4YAg1UAAJNOS4MAg04AAJNXS4MAg1cAAJNYS4FAg1gAAJNXS4FAg1cAAJNVS4FAg1UAAJNTS4FAg1MAAJNaS4kAg1oAAJNcS4FAg1wAAJNeS4FAg14AAJNfS4MAg18AAJNeS4FAg14AAJNcS4FAg1wAAJNaS4MAg1oAAJNXS4MAg1cAAJNcS4MAg1wAAJNaS4FAg1oAAJNYS4FAg1gAAJNXS4MAg1cAAJNVS4MAg1UAAJNTS4FAg1MAAJNSS4FAg1IAAJNTS4FAg1MAAJNXS4FAg1cAAJNVS4MAg1UAAJNQS4FAg1AAAJNTS4FAg1MAAJNTS4YAg1MAAJNVS4RAg1UAAJNaS4FAg1oAAJNcS4MAg1wAAJNaS4FAg1oAAJNcS4FAg1wAAJNaS4MAg1oAAJNVS4FAg1UAAJNYS4FAg1gAAJNYS4MAg1gAAJNXS4FAg1cAAJNVS4FAg1UAAJNUS4MAg1QAAJNVS4FAg1UAAJNXS4FAg1cAAJNYS4MAg1gAAJNXS4FAg1cAAJNVS4FAg1UAAJNTS4MAg1MAAJNVS4MAg1UAAJNTS4wAg1MAgUCTSzIAk04yJINLACiDTgB0k0syAJNOMiSDSwAog04AdJNLMgCTTjIkg0sAKINOAII0k0syAJNOMiSDSwAog04AdJNLMgCTTjIkg0sAKINOAHSTSzIAk04yJINLACiDTgCCNJNQMgCTUzIkg1AAKINTAHSTUDIAk1MyJINQACiDUwB0k1AyAJNTMiSDUAAog1MAgjSTTjIAk1IyJINOACiDUgB0k04yAJNSMiSDTgAog1IAdJNOMgCTUjIkg04AKINSAII0k0syAJNOMiSDSwAog04AdJNLMgCTTjIkg0sAKINOAHSTSzIAk04yJINLACiDTgCCNJNLMgCTTjIkg0sAKINOAHSTSzIAk04yJINLACiDTgB0k0syAJNOMiSDSwAog04AgjSTTjIAk1IyJINOACiDUgB0k04yAJNSMiSDTgAog1IAdJNOMgCTUjIkg04AKINSAHSTUDIAk1MyJINQACiDUwB0k1AyAJNTMiSDUAAog1MAdJNOMgCTUjIkg04AKINSAHSTTjIAk1IyJINOACiDUgCCNJNQMgCTUzIkg1AAKINTAHSTUDIAk1MyJINQACiDUwB0k1AyAJNTMiSDUAAog1MAgjSTTjIAk1IyJINOACiDUgB0k04yAJNSMiSDTgAog1IAdJNOMgCTUjIkg04AKINSAII0k0wyAJNQMiSDTAAog1AAdJNMMgCTUDIkg0wAKINQAHSTTDIAk1AyJINMACiDUACCNJNLMgCTTjIkg0sAKINOAHSTSzIAk04yJINLACiDTgB0k0kyAJNMMiSDSQAog0wAgjSTSzIAk04yJINLACiDTgB0k0syAJNOMiSDSwAog04AdJNLMgCTTjIkg0sAKINOAII0k0wyAJNQMiSDTAAog1AAdJNMMgCTUDIkg0wAKINQAHSTTDIAk1AyJINMACiDUACCNJNJMgCTTDIkg0kAKINMAHSTSTIAk0wyJINJACiDTAB0k0kyAJNMMiSDSQAog0wAdJNSMgCTVTIkg1IAKINVAHSTUDIAk1MyJINQACiDUwB0k04yAJNSMiSDTgAog1IAdJNLMgCTTjIkg0sAKINOAII0k1AyAJNTMiSDUAAog1MAdJNQMgCTUzIkg1AAKINTAHSTUDIAk1MyJINQACiDUwCCNJNOMgCTUjIkg04AKINSAHSTTjIAk1IyJINOACiDUgB0k04yAJNSMiSDTgAog1IAhTSTSzIAk04yJINLACiDTgCCNJNIMgCTSzIkg0gAKINLAHSTSDIAk0syJINIACiDSwB0k0gyAJNLMiSDSAAog0sAgjSTTDIAk1AyJINMACiDUAB0k0wyAJNQMiSDTAAog1AAdJNMMgCTUDIkg0wAKINQAII0k0kyAJNMMiSDSQAog0wAdJNJMgCTTDIkg0kAKINMAHSTSTIAk0wyJINJACiDTACCNJNHMgCTSzIkg0cAKINLAHSTSzIAk04yJINLACiDTgB0k0kyAJNMMiSDSQAog0wAdJNHMgCTSzKDAINHAACDSwCEQJNMMgCTUDIkg0wAKINQAHSTTDIAk1AyJINMACiDUAB0k0wyAJNQMiSDTAAog1AAgjSTSTIAk0wyJINJACiDTAB0k0kyAJNMMiSDSQAog0wAdJNJMgCTTDIkg0kAKINMAII0k0cyAJNLMiSDRwAog0sAdJNLMgCTTjIkg0sAKINOAHSTSTIAk0wyJINJACiDTAB0k0cyAJNLMoMAg0cAAINLAAD/LwA=";

    data = atob(data);

    midi = new Midi(data);

    mixer = new Mixer();
    midi.add_callback(function(e){e.note_number-=12;mixer.handle_event(e);});
    midi.add_callback(function(e){
        if(e.type == 0x9){
            notes[e.note_number+","+e.midi_channel] = {
                    x:(e.midi_channel+1),
                    y:9*2-e.note_number*0.2,
                    maxtimeleft:e.time_to_next_sameevent,
                    timepassed:0,
                    color: COLORS[e.midi_channel]
                };
        }
        else if(e.type == 0x8){
            delete notes[e.note_number+","+e.midi_channel];
        }
    });

}



